version: "3"
volumes:
    pgdata:

services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgAdmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_PASSWORD=root
            - PGADMIN_DEFAULT_EMAIL=admin@email.com
            - PGADMIN_LISTEN_PORT=80
        ports:
            - 8090:80